### ISSUE TITLE
Cache mechanism

### ISSUE THREAD

**Issue by bestlibre** [Cyr-ius/cozytouchpy#4]
This is a continuation of https://github.com/biker91620/cozypy/issues/7

I will try to get the json ASAP.

I'm still thinking that if it is possible to get the data for all the devices in one call, it should be done. I have 9 heaters and there's at least one call to the API for each of them. I'm suspecting more, one for each sensor in home assistant.

**Comment by Cyr-ius** [comment]
I completely agree, if we want to limit the number of calls, we must necessarily implement an HA coordinator, because HA is basically designed to make a call by entity.
It is not a problem for me to do so.

The problem is not the HA plugin but the Cozytouchpy API which is written to make many calls.

I started from this API because unfortunately I do not have enough elements to write an API which correctly exploits the Overkiz json for all devices.

**Comment by bestlibre** [comment]
If you call 'https://ha110-1.overkiz.com/enduser-mobile-web/enduserAPI/setup' instead of 'https://ha110-1.overkiz.com/enduser-mobile-web/enduserAPI/setup/devices' you get a json with more information (bidge, rooms, place, etc). But for the devices data I think that the 'setup/devices' url is sufficient.

[This is a json](https://gist.github.com/bestlibre/8fdaee9ae8610cdd1e3609f34003330c) with the information from one heater. Let me know if I can try something.

**Comment by Cyr-ius** [comment]
Very good
I'm rewriting the cozytouch API to make it much easier to use in the HA plugin

**Comment by bestlibre** [comment]
I will not have the time to propose a PR porting the new logic (from the hotfix branch) to the heater. But if you can do it, I will test it

**Comment by bestlibre** [comment]
Have you made some progress on the cozytouchpy rewrite ?

I have found [this doc](https://developers.home-assistant.io/docs/integration_fetching_data#coordinated-single-api-poll-for-data-for-all-entities) about the coordinator in home-assistant. I think this is probably the right way to integrate cozytouch in home assistant :

- use the coordinator in hass-cozytouch to coordinate updates
- add an endpoint in cozytouchpy to fetch all the data (this is actually the client.get_devices method, wit small changes to the return data for easier integration in hass-cozytouch)

Your modification of water_heater in hass-cozytouch goes in the right direction, but the use of the coordinator will permit to exploit data in climate, sensor and binary_sensor.

**Comment by bestlibre** [comment]
I have looked at the problem again, and I think I have a solution. With the switch to asynchronous logic it is possible to keep the update in the main thread and this simplify the caching of the data. I have made two pull request, [in this project](https://github.com/Cyr-ius/cozytouchpy/pull/7) and [in the home assistant integration](https://github.com/Cyr-ius/hass-cozytouch/pull/9)
This is still a work in progress but it is working. I have dramatically reduced the number of calls to the API.

What are you thinking of these PR ?

**Comment by Cyr-ius** [comment]
the first version that I modified of biker had been to carry it entirely in asynchronous unfortunately in the new version of HomeAssisant, I encountered problems because it controls the calls in their loop of events and I thus made a roll back.
I will test again with your PR
My first version with asyncio
https://github.com/Cyr-ius/cozytouchpy/tree/v1.5.0/cozytouchpy

**Comment by bestlibre** [comment]
I have switched from requests to aiohttp which is asyncio friendly.

**Comment by Cyr-ius** [comment]
I just released a beta version of cozytouch with your PR
https://pypi.org/project/cozytouchpy/1.6.2b0/

I just tested the component in HA. Everything seems good to me. I finish my tests and if everything is OK, I push a version tomorrow
